AWSTemplateFormatVersion: "2010-09-09"
Description: an ec2 creation using template
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      
    Description: Enter t3.micro, t3.small, or t3.medium. Default is t3.micro.

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
        
      ImageId: ami-08766f81ab52792ce 

#Outputs:
#parameter referencing
